### ISSUE TITLE
BUG: Unauthorized export after setting basic authentication

### ISSUE THREAD

**Issue by seb0uil** [dbgate/dbgate#503] opened 2023-02-21 18:17 UTC
**Describe the bug**
Hi,
After setting basic auth using `LOGINS` and `LOGIN_PASSWORD` env variable, I can't download exported file.
The generated URL (http://xxx/uploads/get?file=xxx) is unauthorized with 401 Code

**To Reproduce**
1. docker run --rm -it -e LOGINS=test -e LOGIN_PASSWORD_test=test -p 3000:3000 dbgate/dbgate:beta-alpine
2. create new connexion
3. In any table, in contextual menu, i choose export/JSON (for example, but same with all exports)
4. i got a redirection to http://127.0.0.1:3000/uploads/get?file=2b80a500-b212-11ed-892a-7b4d8c085e2a.json which is unauthorized (status 401)

**Expected behavior**
The generated URL is authorized after authentication

**Version Information (please complete the following information):**
 - App Version: 5.2.3-beta.8. / Build date: 2023-02-19
 - docker `dbgate/dbgate:beta-alpine`  same with `dbgate/dbgate`
 - Type - Web
 - Database engine: PostgreSQL

**Comment by barry-luijten** [comment] 2023-04-03 06:35
I am experiencing the same behaviour. Observed message in the console:
```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (internal/errors.js:322:7)
    at ServerResponse.setHeader (_http_outgoing.js:561:11)
    at ServerResponse.E.set.E.header (/home/dbgate-docker/bundle.js:577:6822)
    at ServerResponse.E.send (/home/dbgate-docker/bundle.js:577:2440)
    at h (/home/dbgate-docker/bundle.js:610:100609)
    at authMiddleware (/home/dbgate-docker/bundle.js:610:102476)
    at s.handle_request (/home/dbgate-docker/bundle.js:417:784)
    at /home/dbgate-docker/bundle.js:403:2982
    at /home/dbgate-docker/bundle.js:403:3004
    at Function.m.process_params (/home/dbgate-docker/bundle.js:403:3517)
```

**Comment by mcasaccio** [comment] 2023-04-14 19:52
same issue here

**Comment by argaar** [comment] 2023-06-06 16:54
I can confirm the bug, it also happened to me with npm deploy and also withdocker ones.
It happens with Basic Auth and with AD Auth as well, the only workaround I've found at the moment is to use nginx as reverse proxy (I'm using the docker version) with an htpasswd file (that would ends up to mimic the Basic Auth)

My goal is to use it in production but without AD Auth (however is not a problem strictly related to AD) this won't be possibile

**Comment by Naude555** [comment] 2023-06-28 06:50
Having the same issue with docker-compose after setting up basic auth

**Comment by saleembasit** [comment] 2023-10-03 06:59
Any update on this issue?

**Comment by argaar** [comment] 2023-10-03 10:29
don't know if this could resolve (https://github.com/dbgate/dbgate/pull/627), but it has been merged 5d ago.
hope we'll see something in the next release

**Comment by saleembasit** [comment] 2023-10-03 10:57
> don't know if this could resolve (#627), but it has been merged 5d ago. hope we'll see something in the next release

Thank you for the update.

It looks promising, looking forward to next release.

**Comment by saleembasit** [comment] 2023-10-09 07:53
Just upgraded to 5.2.7, and the issue is still there.

My setup is;
a) Debian 11.7
b) Installed using sudo npm install -g dbgate-serve@5.2.7
c) sudo pm2 stop dbgate-serve && sudo pm2 start dbgate-serve ./ecosystem.config.js && sudo pm2 save
d) cat ./ecosystem.config.js
module.exports = {
  apps : [
      {
        name: "dbgate-serve",
        watch: true,
        env: {
          "LOGINS": "xxx",
          "LOGIN_PASSWORD_xxx": "<some_password>,
        },
        LOG_LEVEL: "debug"
      }
  ]
}

e) when I try to export data, the popup appears 'Exporting data..' and then in a new browser window, 'Unauthorized' is printed, with URL https://<host>/dbgate/uploads/get?file=<name>.xlsx 

f) this is printed in log;
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:530:11)
    at ServerResponse.header (/usr/local/lib/node_modules/dbgate-serve/node_modules/express/lib/response.js:794:10)
    at ServerResponse.send (/usr/local/lib/node_modules/dbgate-serve/node_modules/express/lib/response.js:174:12)
    at unauthorizedResponse (/usr/local/lib/node_modules/dbgate-serve/node_modules/dbgate-api/src/controllers/auth.js:29:30)
    at authMiddleware (/usr/local/lib/node_modules/dbgate-serve/node_modules/dbgate-api/src/controllers/auth.js:59:12)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/dbgate-serve/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/dbgate-serve/node_modules/express/lib/router/index.js:328:13)
    at /usr/local/lib/node_modules/dbgate-serve/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/usr/local/lib/node_modules/dbgate-serve/node_modules/express/lib/router/index.js:346:12)
    at next (/usr/local/lib/node_modules/dbgate-serve/node_modules/express/lib/router/index.js:280:10)

g) Note that the proper file <name>.xlsx exists on server. I can scp to my client and the data is perfectly fine.

**Comment by lalienagabriel** [comment] 2023-10-17 14:53
Hi there.
I´ve the same issue while trying to use Oauth, can´t do an export of the data because once the file it´s generated you are being redirected to unauthorized page.
Once i´ve disabled the oauth, it has started working, also i´ve tried to switch to dbgate auth but same issue.
I´ve updated dbgate to 5.2.7 but the issue still there.
Here are the logs related to the headers:
`Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (internal/errors.js:322:7)
    at ServerResponse.setHeader (_http_outgoing.js:561:11)
    at ServerResponse.E.set.E.header (/home/dbgate-docker/bundle.js:577:6822)
    at ServerResponse.E.send (/home/dbgate-docker/bundle.js:577:2440)
    at h (/home/dbgate-docker/bundle.js:610:100708)
    at authMiddleware (/home/dbgate-docker/bundle.js:610:102575)
    at s.handle_request (/home/dbgate-docker/bundle.js:417:784)
    at /home/dbgate-docker/bundle.js:403:2982
    at /home/dbgate-docker/bundle.js:403:3004
    at Function.m.process_params (/home/dbgate-docker/bundle.js:403:3517)`

**Comment by mbrekhov** [comment] 2023-12-08 16:54
Hi!

I see that the problem is with **exportFileTools** function (https://github.com/dbgate/dbgate/blob/aa7d91f2c5824a0938f7cc22a3aa4ae2c84cbf39/packages/web/src/utility/exportFileTools.ts#L190)

It doesn't pass **_Authorization_** header during GET request to a file. That's why we've got "Unauthorized" message in browser.
![image](https://github.com/dbgate/dbgate/assets/41376938/468d713d-57fd-4cea-8a56-dec0201806a6)

Here is the **POST** request that generates a file
![image](https://github.com/dbgate/dbgate/assets/41376938/07e9b1c7-8bab-4efb-b294-a0d527534f70)

Here is the **GET** request which is trying to download the file:
![image](https://github.com/dbgate/dbgate/assets/41376938/b9b26239-73ff-4f0c-be72-bb53c78fb465)

**Closed** 2024-01-04 22:46 UTC
