### ISSUE TITLE
FEAT: Request to release dbgate to flathub.

### ISSUE THREAD

**Issue by tirtharajsinha** [dbgate/dbgate#771] opened 2024-05-08 22:49 UTC
I'm a long time dbeaver user. Tried dbgate and It's amazing. Loved it. Currently using appimage. I know I can create a .desktop file but It's a lot of work and snap sucks.

So, It's a request to add dbgate to flathub.

**Comment by ProjectInfinity** [comment] 2024-05-08 23:07
Duplicate of https://github.com/dbgate/dbgate/issues/297

**Closed by ProjectInfinity** 2024-05-08 23:07 UTC
