### ISSUE TITLE
BUG: Missing file chooser fonts in snap package 

### ISSUE THREAD

**Issue by m-fariz-a** [dbgate/dbgate#841] opened 2024-06-22 07:56 UTC
I want to open sqlite3 database and found that the font from the snap package is not readable within file chooser. It happenned also when exporting table to local file.

**Screenshots**
![image](https://github.com/dbgate/dbgate/assets/73702296/c471994a-fea9-4a16-a8cd-090cb8f68c01)

**Version Information:**
 - OS: Ubuntu 24.04
 - App Version : 5.3.1
 - Install source : Snap

**Comment by ProjectInfinity** [comment] 2024-06-22 15:06
I believe this is just a Ubuntu issue and it is not related to DbGate. I found many similar issues searching with other snaps.

**Comment by ProjectInfinity** [comment] 2024-06-22 16:47
You should be able to find a solution here:
https://askubuntu.com/a/1228809

Please let me know if that sorts out your issue.

**Comment by m-fariz-a** [comment] 2024-06-23 01:43
Thank you for the solution. It works.
Unfortunately, I think this is not Ubuntu problem, but with snaps problem. 
Last week, I try to install the snap version in Fedora 40 on my office and had the same problem.

Thanks a lot.

**Comment by ProjectInfinity** [comment] 2024-06-24 14:35
Aha. Yes I just assume everyone using snaps are on Ubuntu. Generally you shouldn't use snaps outside of Ubuntu since the sandboxing doesn't work by default there.

Anyway since the issue is solved I will be closing this.

**Closed by ProjectInfinity** 2024-06-24 14:35 UTC
