### ISSUE TITLE
FEAT: 希望字段列能显示字段的备注

### ISSUE THREAD

**Issue by wuqiyin** [dbgate/dbgate#218] opened 2022-02-09 03:11 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by janproch** [comment] 2022-02-09 06:34
Please better use English 

Translation: want the field column to display the field's comments

**Comment by janproch** [comment] 2022-02-09 06:35
Duplicate of #81

**Comment by wuqiyin** [comment] 2022-02-09 06:50
yes！i want the field column to display the field's comments



***@***.***
 
发件人： Jan Prochazka
发送时间： 2022-02-09 14:34
收件人： dbgate/dbgate
抄送： silverwq; Author
主题： Re: [dbgate/dbgate] FEAT: 希望字段列能显示字段的备注 (Issue #218)
Please better use English
Translation: want the field column to display the field's comments
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by janproch** [comment] 2022-02-10 19:31
Column description for MySQL (both display and modify)  is available in latest BETA, 4.6.1-beta.1

**Comment by janproch** [comment] 2022-02-21 19:25
Released in 4.7.0

**Closed by janproch** 2022-02-21 19:25 UTC
Labels: accepted+planned
