### ISSUE TITLE
Error: There is nothing to be shown on map

### ISSUE THREAD

**Issue by dataspun** [dbgate/dbgate#307] opened 2022-07-05 22:47 UTC
**Describe the bug**
Geometry data fails to open in map view.  Instead the data appears to be interpreted as text, and an error is displayed when attempting to open a map.  Noteworthy: same data opens in map using pgAdmin tool (see sample data below).

**To Reproduce**
1. Select geometry data cells
2. Right click: 'Open selection in map' (alternatively, Click the navigation option Cell Data View)
3. See error modal: 'There is nothing to show on map' (alternatively, note the format Autodetect - Text)

**Expected behavior**
Open geometry data in map view (as shown [in docs](https://dbgate.org/docs/maps.html)).

**Sample geometry data**
"0106000020E61000000100000001030000000100000023000000B8E7667199065DC000DFDB89317F454094DF0E0394065DC0A8556C8A267F4540B42149758E065DC0800692461B7F454038BDC9728A065DC0B067A0670D7F454044D8C2C68B065DC0987ADC41687E45409C3DC3028B065DC040ADB363597E4540082DDD688B065DC040773BE5517E4540C436BBFF94065DC0F8A441AC3A7E45400060D0C39E065DC068F007262F7E4540781006A7AA065DC0C8B723A5257E45403403F938B7065DC040E5930F1F7E4540FC1C6186BD065DC020D8F6A61E7E454008AF8819BF065DC0587D8D0A1A7E4540443BF6CDC2065DC028443584197E4540041A9B4FDA065DC068B45F392E7E45402C6B1455DF065DC06894130D387E4540F86514B7F2065DC0C00E8A2C567E4540940C2155FD065DC0A09E81D3647E454098C8C19119075DC028D0D460AC7E4540D0899E2C26075DC0C053B521D67E4540BCA1D7BD25075DC040A9BB5FFB7E4540E4FC04A91C075DC048529A811C7F4540440095EF16075DC0788555B5287F45401C23CE5910075DC008DBB317347F45404877A9C408075DC080324D8B3E7F4540E0846771FE065DC000B0937C487F4540C41E827BF4065DC09892E4EE4E7F454050E3F2CFD7065DC0F8AA7863507F454024398810CE065DC0E08924C0517F4540BCE7E129C3065DC078CFBE54507F45401C882C80BA065DC0E8701A66497F4540C0001CC8B3065DC0D07EE335457F454090FCAF0BA8065DC0C8A1E2CF437F454068ACACFA9F065DC0F03026693B7F4540B8E7667199065DC000DFDB89317F4540"

**Version Information**
 - OS: Windows 11
 - App Version 5.0.6
 - Install source: installer
 - Type: application
 - Database engine: PostgreSQL

**Comment by janproch** [comment] 2022-07-11 18:58
Do you have some screehshot or this situation? 

I tried it with you geography data and it seems to work

When browsing table data, there is a condition, geometry is shown only, when detected type is geography

Also there should be text representation of geography in data shown in cell. If you have geography as result of a query, you must convert it to text to be shown in dbgate (in PostgreSQLit is function ST_AsText) 

![image](https://user-images.githubusercontent.com/2543891/178337436-25d3173e-cf52-4f8c-aef9-81763e67f9d0.png)

**Comment by dataspun** [comment] 2022-07-11 23:10
Thanks!  ```ST_AsText()``` works as you described on the provided binary geometry data.  In the screenshot above, the binary value was placed into a geography column, which facilitated the map view.  Are there considerations to enhancing dbgate, such that the same geometry data, whether geography, text or binary, displays in map view?

**Comment by janproch** [comment] 2022-07-17 14:32
I would like do do this
Now I use package wellknown for parsing text geometry, this works well, but doesn't support binary data
There is package wkx, which could do that, however, this package could not be used with rollup. It seems now unmaintained. 
There is fork of wkx package from Rich Harris (author of Svelte), which solves this, but it is not merged into package. The problem is described here: https://github.com/cschwarz/wkx/issues/24
 
If someone want to make new version of wkx working with rollup, it would be great. I would like to do that, but now I have no time for this.

**Comment by ezwelty** [comment] 2024-02-07 15:05
> When browsing table data, there is a condition, geometry is shown only, when detected type is geography

Is there a reason to require the `geography` type? Both `geometry` and `geography` PostGIS types store coordinates in some specified spatial reference system and I presume would be equivalent to DbGate for displaying well known text and displaying on map.

I have a database that uses the `geometry` type (but with a geographic CRS because the data is global in extent) for performance reasons.

**Comment by pankus** [comment] 2024-03-09 17:55
Thus, if I understand well, to plot the geometries with a map viewer, the WKB data must be converted into text. 
For instance:
```sql
SELECT id, placename, ST_AsText(point)
from placenames
where point is not null
```
Can the same be performed with the WKB data type?

**Comment by dataspun** [comment] 2024-03-09 18:16
@pankus not clear what you're asking but perhaps this [postgis doc](https://postgis.net/docs/using_postgis_dbmanagement.html#OpenGISWKBWKT) helps.  the original issue described above with dbgate is that rendering geometry in map view requires an additional conversion step. WKB as binary would likely require the same, should be easy to confirm either way.

**Comment by pankus** [comment] 2024-03-09 18:43
Dear @dataspun , first of all, I would like to thank you for making this outstanding software available. I started testing its functionality this afternoon, and I am literally blown away.
Regarding the issue I tried to highlight, I realized that the "data view" map seems to work on the fly only when the data is saved in WKT format (see also the screenshots in this thread or those in the documentation), like POINT(47.611336 34.192902). If the same data is saved in WKB format (0101000020E61000096F0F4240CE47409FAA4203B1184140), the map is not displayed.
In my experience, saving geographic data in binary format is quite common. I was wondering if DbGate can convert from WKB to WKT on its own (if I remember correctly, PGAdmin4 does it). 
This is not a big deal: it is enough for the user to perform a trivial query like the one above. 
Perhaps it would be important to make this explicit in the documentation, though.

**Comment by dataspun** [comment] 2024-03-09 22:04
All credit for dbgate goes to @janproch. I think we're all aligned on what the issue is here, and I would love to submit a patch.  Still on my radar.

**Comment by ezwelty** [comment] 2024-03-15 09:28
> I think we're all aligned on what the issue is here, and I would love to submit a patch. Still on my radar.

@dataspun It seems like there are a few different overlapping issues?

When opening a table, since the structure is known, DBGate automatically wraps columns in `ST_AsText` to get geometries as WKT. My comment above (https://github.com/dbgate/dbgate/issues/307#issuecomment-1932241897) points out that for PostgreSQL driver, this should be for both `geography` and `geometry` column types, not just `geography`.

Geometries returned by a query must be formatted as WKT to be displayed on the map. If the result is WKB, the user must use `ST_AsText` to convert to WKT. A fix would be to infer WKB columns (as is done for WKT: https://github.com/dbgate/dbgate/blob/10801470851351a4f4aa5b4d07087462c0d03969/packages/tools/src/stringTools.ts#L91C17-L91C30) based on the [first bytes](https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry#Well-known_binary) and parse/convert WKB client-side. This would also avoid the need to overload the SELECT statements for tables described above. Alternatively, one could fetch the data types of the result and then overload the query to return WKT, but this really feels like a hack.

It is worth noting that PostGIS natively returns hexadecimal representation of EWKB (https://postgis.net/docs/manual-3.0/using_postgis_dbmanagement.html#EWKB_EWKT), meaning the coordinate system is also included (use `ST_AsEWKT` for the WKT equivalent). Would it be realistic to switch from Leaflet to OpenLayers? The latter supports (E)WKB (https://openlayers.org/en/latest/apidoc/module-ol_format_WKB-WKB.html), which would both take care of parsing WKB and  add support for different coordinate systems.

Not yet mentioned, but related: Tables with very large geometries (e.g. national borders) are basically unusable in DBGate, presumably because it is injecting huge amounts of data into each cell and not because the application runs out of memory (because other tabs remain responsive). Probably a cutoff is needed, such that only the first part is displayed, and the rest is stored in the background?

**Closed** 2024-11-22 07:28 UTC
Labels: good first issue

**Comment by dataspun** [comment] 2024-11-26 21:35
@janproch not sure if you'd rather reopen this issue or not, but #914 didn't seem to fix as hoped:

Postgres geometry columns are now being detected as USER-DEFINED data type rather than GEOMETRY.

Also, something has changed since your [initial comment above](https://github.com/dbgate/dbgate/issues/307#issuecomment-1180755852), even Postgres geography columns are detected as USER-DEFINED rather than GEOGRAPHY.

If I try to change the data type using the Edit Column interface, I'm given options such as Line, Point, and Polygon but these aren't actual data types in Postgres.

This all seems contrary to what is [described in documentation](https://dbgate.org/docs/maps.html).  Any ideas on how to bridge the gap such that Postgres GEOGRAPHY and GEOMETRY data types are auto-detected as Map in Cell Data View?

Using `ST_AsText()` still works for both, but it's not ideal because you can't just open/query an object as-is and get the spatial view.
