### ISSUE TITLE
BUG: Cannot find better-sqlite3

### ISSUE THREAD

**Issue by Meniny** [dbgate/dbgate#775] opened 2024-05-10 10:46 UTC
**Describe the bug**
I have a sqlite3 database file, which I can connect to via DBGate 5.2.7 on my computer (amd64, ubuntu 22.04, kernel 6.8.0).
But I can't do the same thing on my raspberry pi (aarch64, bookworm, kernel 6.6.28).

I got this error:

```
Connect failed:  /tmp/.mount_dbgatefoIbP4/resources/app.asar.unpacked/node_modules/better-sqlite3/build/Release/better_sqlite3.node: cannot open shared object file: No such file or directory Show detail
```

**To Reproduce**
1. New connection
2. Choose SQLite
3. Select the db.sqlite3 file
4. Click "Connect"/"Test"

**Version Information (please complete the following information):**
 - OS: Raspberry Pi OS with kernel version 6.6.28, aarch 64, bookworm
 - App Version: 5.2.7
 - Install source: AppImage
 - Type: Application
 - Database engine: SQLite3

**Comment by Meniny** [comment] 2024-05-10 10:47
I installed better-sqlite3 via command `npm install -g better-sqlite3`, but nothing changed.

**Comment by ProjectInfinity** [comment] 2024-05-10 11:07
Closing this as it is a duplicate issue.

The issue is related to ARM builds. Meaning macOS devices with M1/2/3 chips and devices such as Raspberry Pi. It's something that has been on our radar for a long time but requires some bigger changes to how the application is built to resolve.

**Closed by ProjectInfinity** 2024-05-10 11:07 UTC
