### ISSUE TITLE
BUG: DbGate for Docker, Connection Error with nginx

### ISSUE THREAD

**Issue by koenigmarcel** [dbgate/dbgate#222] opened 2022-02-11 10:01 UTC
Hi,
i'm using DbGate for Docker. To secure my Webpage with a Password i'm using nginx (http auth).
Nginx just fowards the port to another port with a simple http authentication in front of the webpage.

When im connecting to the forwarded port sometimes the connection to the Database fails until i refresh the page.
Then the Databases are continuously loading until i refresh the page a second time.

This Bug doesn't appear everytime, maybe every 10th time or maybe all 15 minutes.

Apart from that an intern http authorization / simple login / etc. in dbgate could be a nice extra feature.

![Screenshot 2022-02-11 104725](https://user-images.githubusercontent.com/54361017/153571310-4f5fbe44-0c89-4299-bc04-32e996071099.png)
-> Refresh
![Screenshot 2022-02-11 104753](https://user-images.githubusercontent.com/54361017/153571314-03078b5a-f07d-4fbd-977e-3145c2c263e3.png)
-> Refresh
![Screenshot 2022-02-11 104833](https://user-images.githubusercontent.com/54361017/153571316-26fed8a7-feb5-4d9b-9137-f756ddc5d3d6.png)

 - OS: Debian
 - App Version 4.6.1 (But also Versions before)
 - Install source Docker
 - Type - Web
 - Database engine: PostgreSQL

Edit:
The Problem also occurs without nginx, but then the connection errors just for a milisecond and then establishes
(You can see the '(x)' logo for a very short time)

**Comment by janproch** [comment] 2022-02-11 15:46
Hello,

thanks for reporting.

Could you please try current beta, if the problem is solved? It is available under beta tag

docker pull dbgate/dbgate:beta

It seems to be very similar to issue #219, which I hopefully solved yesterday

Very simple login and password in web version is already supported, use environment variables LOGIN and PASSWORD. But with nginx as reverse proxy it should also work.

**Comment by koenigmarcel** [comment] 2022-02-14 12:18
> Hello,
> 
> thanks for reporting.
> 
> Could you please try current beta, if the problem is solved? It is available under beta tag
> 
> docker pull dbgate/dbgate:beta
> 
> It seems to be very similar to issue #219, which I hopefully solved yesterday
> 
> Very simple login and password in web version is already supported, use environment variables LOGIN and PASSWORD. But with nginx as reverse proxy it should also work.



> Hello,
> 
> thanks for reporting.
> 
> Could you please try current beta, if the problem is solved? It is available under beta tag
> 
> docker pull dbgate/dbgate:beta
> 
> It seems to be very similar to issue #219, which I hopefully solved yesterday
> 
> Very simple login and password in web version is already supported, use environment variables LOGIN and PASSWORD. But with nginx as reverse proxy it should also work.

Hi,
in the new Beta version the Problem is solved.
When is the release?

**Comment by janproch** [comment] 2022-02-15 08:25
Hi,

thanks for testing.
Now, release is planned to Monday 2022-02-20, but because there are lot of changes in this release, it could take a bit longer to make it stable

**Comment by janproch** [comment] 2022-02-21 19:25
Released in 4.7.0

**Closed by janproch** 2022-02-21 19:25 UTC
