### ISSUE TITLE
BUG: DbGate creates a lot of .tmp.node files in the temp directory

### ISSUE THREAD

**Issue by Sympatron** [dbgate/dbgate#561] opened 2023-05-22 08:50 UTC
First of all I want to say that DbGate is an extremely helpful open source software and greatly appreciated.

**Describe the bug**
While DbGate is running it creates 2 `<guid>.tmp.node` files per minute of exactly 1418240 Bytes. This adds up to over 4GB per day. As far as I can see these are never cleaned up.
The problem seems to be that DbGate spawns two short lived child processes every minute. Node.js probably then creates those files on startup, but does not delete them on exit.

I suspect this is really an electron thing, but other electron apps I use don't exhibit this behavior so I think it can be solved in DbGate.

**To Reproduce**
1. Start DbGate
2. I don't know if you need to connect to a SQL Server for this to happen
3. Wait a few minutes
4. Search %TEMP%\\*.tmp.node

**Expected behavior**
Either DbGate should not produce these files or clean them up.

**Version Information:**
 - OS: Windows
 - App Version: 5.2.5
 - Install source: Installer
 - Type: Application
 - Database engine: SQL Server

**Comment by Sympatron** [comment] 2023-05-22 08:53
I'm not quite sure yet when this starts. While looking deeper into this it sometimes stops happening for a while. At the moment I suspect it starts when Windows goes into energy saving mode (monitors off) or when Windows is locked, but I am not sure. I will update this issue if I can reproduce it more reliably.

**Comment by janproch** [comment] 2023-05-26 12:32
Thanks, I replicated it, it seems to be caused by msnodesqlv8 package

**Comment by janproch** [comment] 2023-05-26 16:15
It is "almost" solved now. The problem occurs with all native modules (sqlite, mssql with SQL server authentication, OracleDB). Now tmp files are created only when you use one of these connections. It is not final solution, but it is much better now and most people will not encounter this issue now.

**Comment by janproch** [comment] 2023-05-27 06:29
Definitely fixed now. Used workaround https://github.com/electron/electron/issues/10139

**Closed** 2023-06-02 11:29 UTC
Labels: solved, Released in BETA
